// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/internal/conf/v1/gateway.proto

// The package mirrors this file's directory relative to the buf module root
// (the monorepo's app/ dir), which keeps it unique per service — the gateway's
// conf messages (Bootstrap, Server, ...) share names with every service
// template's — and satisfies buf lint PACKAGE_DIRECTORY_MATCH /
// PACKAGE_VERSION_SUFFIX.

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration for the gateway.
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Log           *Log                   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Registry      *Registry              `protobuf:"bytes,4,opt,name=registry,proto3" json:"registry,omitempty"`
	Middleware    *Middleware            `protobuf:"bytes,5,opt,name=middleware,proto3" json:"middleware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetMiddleware() *Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

// Server configures the HTTP transport the gateway listens on.
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

// Gateway configures routing and cross-origin policy.
type Gateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Routes map request path prefixes to backend services.
	Routes []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Cors policy applied to every matched request. Optional.
	Cors          *Cors `protobuf:"bytes,2,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Gateway) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Gateway) GetCors() *Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

// Route forwards one path prefix to a backend service.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path prefix matched against the incoming request path, e.g. "/v1/users".
	PathPrefix string `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Backend service name as registered in Nacos, without the ".http"
	// suffix, e.g. "user_center".
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Optional prefix rewrite: replaces path_prefix in the forwarded path.
	// Empty keeps the original path unchanged.
	RewritePrefix string `protobuf:"bytes,3,opt,name=rewrite_prefix,json=rewritePrefix,proto3" json:"rewrite_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Route) GetRewritePrefix() string {
	if x != nil {
		return x.RewritePrefix
	}
	return ""
}

// Cors configures the cross-origin resource sharing policy.
type Cors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed origins. "*" allows any origin.
	AllowOrigins []string `protobuf:"bytes,1,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	// Allowed HTTP methods.
	AllowMethods []string `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	// Allowed request headers.
	AllowHeaders []string `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	// Allow cookies and credentials.
	AllowCredentials bool `protobuf:"varint,4,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	// How long browsers may cache the preflight response.
	MaxAge        *durationpb.Duration `protobuf:"bytes,5,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cors) Reset() {
	*x = Cors{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cors) ProtoMessage() {}

func (x *Cors) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cors.ProtoReflect.Descriptor instead.
func (*Cors) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Cors) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

// Log configures the logging backend (standard library log/slog).
type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum log level: "debug", "info", "warn", "error". Default "info".
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// Output target: "stdout", "stderr", or "file". Default "stdout".
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// File path when output is "file". Required in that case.
	FilePath string `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Record encoding: "text", "json", or "color". "color" is a minimal,
	// ANSI-colored single-line format for local development. Default "text".
	Format string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	// Include the source file:line in each record. Default false.
	AddSource bool `protobuf:"varint,5,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"`
	// Force color off even when format is "color" (e.g. CI). Otherwise color is
	// auto-detected — disabled by NO_COLOR, TERM=dumb, or non-tty output.
	NoColor bool `protobuf:"varint,6,opt,name=no_color,json=noColor,proto3" json:"no_color,omitempty"`
	// Size-based rotation of the log file. Applies only when output is "file".
	Rotation      *Log_Rotation `protobuf:"bytes,7,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Log) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Log) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Log) GetAddSource() bool {
	if x != nil {
		return x.AddSource
	}
	return false
}

func (x *Log) GetNoColor() bool {
	if x != nil {
		return x.NoColor
	}
	return false
}

func (x *Log) GetRotation() *Log_Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

// Registry configures the Nacos discovery backend the gateway resolves routes
// through, and the Nacos config center it hot-reloads its own config from.
// The gateway cannot start without discovery, so address is required.
type Registry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nacos server endpoints, comma-separated for a cluster
	// ("host:port,host:port"). REQUIRED.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Nacos namespace ID. Empty uses the public namespace.
	NamespaceId string `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// Nacos group. Empty uses DEFAULT_GROUP.
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// Nacos auth username. Optional.
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Nacos auth password. Keep out of version control.
	Password      string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Registry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Registry) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Registry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Registry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Registry) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Middleware toggles the cross-cutting request middleware the gateway applies.
type Middleware struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rate limiting sheds excess inbound traffic at the edge.
	Ratelimit *RateLimit `protobuf:"bytes,1,opt,name=ratelimit,proto3" json:"ratelimit,omitempty"`
	// Circuit breaking fails fast when a backend service keeps erroring.
	CircuitBreaker *CircuitBreaker `protobuf:"bytes,2,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Middleware) Reset() {
	*x = Middleware{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middleware) ProtoMessage() {}

func (x *Middleware) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middleware.ProtoReflect.Descriptor instead.
func (*Middleware) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Middleware) GetRatelimit() *RateLimit {
	if x != nil {
		return x.Ratelimit
	}
	return nil
}

func (x *Middleware) GetCircuitBreaker() *CircuitBreaker {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

// RateLimit configures gateway-side rate limiting. The gateway registers raw
// reverse-proxy handlers (HandlePrefix), which bypass kratos's middleware
// chain, so limiting runs as an HTTP filter backed by a fixed token bucket —
// the standard edge pattern. One bucket is shared by all routes because the
// limiter is context-free; backend services add adaptive BBR limiting of their
// own (see the service conf RateLimit, which also offers a "bbr" type).
type RateLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable the edge rate-limit filter.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Sustained requests per second allowed across the gateway.
	Qps int64 `protobuf:"varint,2,opt,name=qps,proto3" json:"qps,omitempty"`
	// Burst size (short peak above qps). Defaults to qps when 0.
	Burst         int64 `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *RateLimit) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RateLimit) GetQps() int64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *RateLimit) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

// CircuitBreaker trips per-upstream (one breaker per backend service) when that
// backend keeps failing, so the gateway returns 503 immediately instead of
// piling requests onto a sick service. Backed by sony/gobreaker.
type CircuitBreaker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable per-upstream circuit breaking.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Requests allowed through while half-open to probe recovery. Default 5.
	MaxRequests uint32 `protobuf:"varint,2,opt,name=max_requests,json=maxRequests,proto3" json:"max_requests,omitempty"`
	// How often the closed-state counts reset. Default 30s; durations use
	// protojson seconds format (e.g. "30s").
	Interval *durationpb.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// How long the breaker stays open before probing half-open. Default 30s.
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Failure ratio (0..1) over at least min_requests that trips the breaker.
	// Default 0.6.
	FailureRatio float64 `protobuf:"fixed64,5,opt,name=failure_ratio,json=failureRatio,proto3" json:"failure_ratio,omitempty"`
	// Minimum requests observed before the failure ratio can trip the breaker.
	// Default 20.
	MinRequests   uint32 `protobuf:"varint,6,opt,name=min_requests,json=minRequests,proto3" json:"min_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitBreaker) Reset() {
	*x = CircuitBreaker{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreaker) ProtoMessage() {}

func (x *CircuitBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreaker.ProtoReflect.Descriptor instead.
func (*CircuitBreaker) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *CircuitBreaker) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CircuitBreaker) GetMaxRequests() uint32 {
	if x != nil {
		return x.MaxRequests
	}
	return 0
}

func (x *CircuitBreaker) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *CircuitBreaker) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CircuitBreaker) GetFailureRatio() float64 {
	if x != nil {
		return x.FailureRatio
	}
	return 0
}

func (x *CircuitBreaker) GetMinRequests() uint32 {
	if x != nil {
		return x.MinRequests
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Rotation maps onto lumberjack's rotation knobs. Every field is optional; a
// zero value defers to lumberjack's default (max_size 100 MB; max_backups and
// max_age 0 retain everything; compress off). Applies only when output is
// "file".
type Log_Rotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size in megabytes at which the file is rotated. Default 100.
	MaxSize int32 `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	// Number of rotated files to retain. 0 retains all.
	MaxBackups int32 `protobuf:"varint,2,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	// Number of days to retain rotated files. 0 retains all.
	MaxAge int32 `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	// Compress rotated files with gzip.
	Compress      bool `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_Rotation) Reset() {
	*x = Log_Rotation{}
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Rotation) ProtoMessage() {}

func (x *Log_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_internal_conf_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Rotation.ProtoReflect.Descriptor instead.
func (*Log_Rotation) Descriptor() ([]byte, []int) {
	return file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Log_Rotation) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Log_Rotation) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log_Rotation) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Log_Rotation) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

var File_gateway_internal_conf_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_internal_conf_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"&gateway/internal/conf/v1/gateway.proto\x12\x18gateway.internal.conf.v1\x1a\x1egoogle/protobuf/duration.proto\"\xb9\x02\n" +
	"\tBootstrap\x128\n" +
	"\x06server\x18\x01 \x01(\v2 .gateway.internal.conf.v1.ServerR\x06server\x12;\n" +
	"\agateway\x18\x02 \x01(\v2!.gateway.internal.conf.v1.GatewayR\agateway\x12/\n" +
	"\x03log\x18\x03 \x01(\v2\x1d.gateway.internal.conf.v1.LogR\x03log\x12>\n" +
	"\bregistry\x18\x04 \x01(\v2\".gateway.internal.conf.v1.RegistryR\bregistry\x12D\n" +
	"\n" +
	"middleware\x18\x05 \x01(\v2$.gateway.internal.conf.v1.MiddlewareR\n" +
	"middleware\"\xae\x01\n" +
	"\x06Server\x129\n" +
	"\x04http\x18\x01 \x01(\v2%.gateway.internal.conf.v1.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"v\n" +
	"\aGateway\x127\n" +
	"\x06routes\x18\x01 \x03(\v2\x1f.gateway.internal.conf.v1.RouteR\x06routes\x122\n" +
	"\x04cors\x18\x02 \x01(\v2\x1e.gateway.internal.conf.v1.CorsR\x04cors\"i\n" +
	"\x05Route\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12%\n" +
	"\x0erewrite_prefix\x18\x03 \x01(\tR\rrewritePrefix\"\xd6\x01\n" +
	"\x04Cors\x12#\n" +
	"\rallow_origins\x18\x01 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x02 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x03 \x03(\tR\fallowHeaders\x12+\n" +
	"\x11allow_credentials\x18\x04 \x01(\bR\x10allowCredentials\x122\n" +
	"\amax_age\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\"\xe3\x02\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"add_source\x18\x05 \x01(\bR\taddSource\x12\x19\n" +
	"\bno_color\x18\x06 \x01(\bR\anoColor\x12B\n" +
	"\brotation\x18\a \x01(\v2&.gateway.internal.conf.v1.Log.RotationR\brotation\x1a{\n" +
	"\bRotation\x12\x19\n" +
	"\bmax_size\x18\x01 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x02 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\"\x95\x01\n" +
	"\bRegistry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\tR\vnamespaceId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\xa2\x01\n" +
	"\n" +
	"Middleware\x12A\n" +
	"\tratelimit\x18\x01 \x01(\v2#.gateway.internal.conf.v1.RateLimitR\tratelimit\x12Q\n" +
	"\x0fcircuit_breaker\x18\x02 \x01(\v2(.gateway.internal.conf.v1.CircuitBreakerR\x0ecircuitBreaker\"M\n" +
	"\tRateLimit\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03qps\x18\x02 \x01(\x03R\x03qps\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x03R\x05burst\"\x81\x02\n" +
	"\x0eCircuitBreaker\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fmax_requests\x18\x02 \x01(\rR\vmaxRequests\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12#\n" +
	"\rfailure_ratio\x18\x05 \x01(\x01R\ffailureRatio\x12!\n" +
	"\fmin_requests\x18\x06 \x01(\rR\vminRequestsB7Z5kratos-micro-layout/app/gateway/internal/conf/v1;confb\x06proto3"

var (
	file_gateway_internal_conf_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_internal_conf_v1_gateway_proto_rawDescData []byte
)

func file_gateway_internal_conf_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_internal_conf_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_internal_conf_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_internal_conf_v1_gateway_proto_rawDesc), len(file_gateway_internal_conf_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_internal_conf_v1_gateway_proto_rawDescData
}

var file_gateway_internal_conf_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gateway_internal_conf_v1_gateway_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: gateway.internal.conf.v1.Bootstrap
	(*Server)(nil),              // 1: gateway.internal.conf.v1.Server
	(*Gateway)(nil),             // 2: gateway.internal.conf.v1.Gateway
	(*Route)(nil),               // 3: gateway.internal.conf.v1.Route
	(*Cors)(nil),                // 4: gateway.internal.conf.v1.Cors
	(*Log)(nil),                 // 5: gateway.internal.conf.v1.Log
	(*Registry)(nil),            // 6: gateway.internal.conf.v1.Registry
	(*Middleware)(nil),          // 7: gateway.internal.conf.v1.Middleware
	(*RateLimit)(nil),           // 8: gateway.internal.conf.v1.RateLimit
	(*CircuitBreaker)(nil),      // 9: gateway.internal.conf.v1.CircuitBreaker
	(*Server_HTTP)(nil),         // 10: gateway.internal.conf.v1.Server.HTTP
	(*Log_Rotation)(nil),        // 11: gateway.internal.conf.v1.Log.Rotation
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_gateway_internal_conf_v1_gateway_proto_depIdxs = []int32{
	1,  // 0: gateway.internal.conf.v1.Bootstrap.server:type_name -> gateway.internal.conf.v1.Server
	2,  // 1: gateway.internal.conf.v1.Bootstrap.gateway:type_name -> gateway.internal.conf.v1.Gateway
	5,  // 2: gateway.internal.conf.v1.Bootstrap.log:type_name -> gateway.internal.conf.v1.Log
	6,  // 3: gateway.internal.conf.v1.Bootstrap.registry:type_name -> gateway.internal.conf.v1.Registry
	7,  // 4: gateway.internal.conf.v1.Bootstrap.middleware:type_name -> gateway.internal.conf.v1.Middleware
	10, // 5: gateway.internal.conf.v1.Server.http:type_name -> gateway.internal.conf.v1.Server.HTTP
	3,  // 6: gateway.internal.conf.v1.Gateway.routes:type_name -> gateway.internal.conf.v1.Route
	4,  // 7: gateway.internal.conf.v1.Gateway.cors:type_name -> gateway.internal.conf.v1.Cors
	12, // 8: gateway.internal.conf.v1.Cors.max_age:type_name -> google.protobuf.Duration
	11, // 9: gateway.internal.conf.v1.Log.rotation:type_name -> gateway.internal.conf.v1.Log.Rotation
	8,  // 10: gateway.internal.conf.v1.Middleware.ratelimit:type_name -> gateway.internal.conf.v1.RateLimit
	9,  // 11: gateway.internal.conf.v1.Middleware.circuit_breaker:type_name -> gateway.internal.conf.v1.CircuitBreaker
	12, // 12: gateway.internal.conf.v1.CircuitBreaker.interval:type_name -> google.protobuf.Duration
	12, // 13: gateway.internal.conf.v1.CircuitBreaker.timeout:type_name -> google.protobuf.Duration
	12, // 14: gateway.internal.conf.v1.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gateway_internal_conf_v1_gateway_proto_init() }
func file_gateway_internal_conf_v1_gateway_proto_init() {
	if File_gateway_internal_conf_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_internal_conf_v1_gateway_proto_rawDesc), len(file_gateway_internal_conf_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_internal_conf_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_internal_conf_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_internal_conf_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_internal_conf_v1_gateway_proto = out.File
	file_gateway_internal_conf_v1_gateway_proto_goTypes = nil
	file_gateway_internal_conf_v1_gateway_proto_depIdxs = nil
}
