// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/auth.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest is the request for Register.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login username. Must be unique.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Email address. Must be unique.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Plain-text password. Must be 8-72 characters (bcrypt caps input at 72 bytes).
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Display name (optional).
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Phone number (optional).
	Phone         string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// RegisterReply is the response for Register.
type RegisterReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the newly created user (snowflake int64; JSON string via protojson).
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Login username.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Email address.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_user_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// LoginRequest is the request for Login.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Plain-text password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// TokenPair is a pair of access and refresh tokens.
type TokenPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short-lived access token (JWT, default 2h).
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Long-lived refresh token (JWT, default 7d).
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Access token TTL in seconds.
	ExpiresIn int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Token type. Always "Bearer".
	TokenType     string `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_user_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenPair) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

// LoginReply is the response for Login.
type LoginReply struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tokens *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// User ID (snowflake int64; JSON string via protojson).
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Login username.
	Username      string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_user_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReply) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// LogoutRequest is the request for Logout.
type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token to invalidate. Optional: when omitted, the token is taken
	// from the Authorization header, which the auth middleware already validates.
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// LogoutReply is the response for Logout.
type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_user_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{6}
}

// RefreshTokenRequest is the request for RefreshToken.
type RefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A valid refresh token.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_user_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RefreshTokenReply is the response for RefreshToken.
type RefreshTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReply) Reset() {
	*x = RefreshTokenReply{}
	mi := &file_user_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReply) ProtoMessage() {}

func (x *RefreshTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReply.ProtoReflect.Descriptor instead.
func (*RefreshTokenReply) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenReply) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// ChangePasswordRequest is the request for ChangePassword.
type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current password for verification.
	OldPassword string `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	// New password. Must be 8-72 characters (bcrypt caps input at 72 bytes).
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_user_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordReply is the response for ChangePassword.
type ChangePasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReply) Reset() {
	*x = ChangePasswordReply{}
	mi := &file_user_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReply) ProtoMessage() {}

func (x *ChangePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReply.ProtoReflect.Descriptor instead.
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return file_user_v1_auth_proto_rawDescGZIP(), []int{10}
}

var File_user_v1_auth_proto protoreflect.FileDescriptor

const file_user_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/auth.proto\x12\vapi.user.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xd7\x01\n" +
	"\x0fRegisterRequest\x12+\n" +
	"\busername\x18\x01 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18@R\busername\x12&\n" +
	"\x05email\x18\x02 \x01(\tB\x10\xe0A\x02\xbaH\n" +
	"\xc8\x01\x01r\x05\x18\xff\x01`\x01R\x05email\x12+\n" +
	"\bpassword\x18\x03 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x10\b\x18HR\bpassword\x12#\n" +
	"\bnickname\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18@R\bnickname\x12\x1d\n" +
	"\x05phone\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18 R\x05phone\"Z\n" +
	"\rRegisterReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\\\n" +
	"\fLoginRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\busername\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\bpassword\"\x91\x01\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\"q\n" +
	"\n" +
	"LoginReply\x12.\n" +
	"\x06tokens\x18\x01 \x01(\v2\x16.api.user.v1.TokenPairR\x06tokens\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\r\n" +
	"\vLogoutReply\"E\n" +
	"\x13RefreshTokenRequest\x12.\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\frefreshToken\"C\n" +
	"\x11RefreshTokenReply\x12.\n" +
	"\x06tokens\x18\x01 \x01(\v2\x16.api.user.v1.TokenPairR\x06tokens\"y\n" +
	"\x15ChangePasswordRequest\x12,\n" +
	"\fold_password\x18\x01 \x01(\tB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\voldPassword\x122\n" +
	"\fnew_password\x18\x02 \x01(\tB\x0f\xe0A\x02\xbaH\t\xc8\x01\x01r\x04\x10\b\x18HR\vnewPassword\"\x15\n" +
	"\x13ChangePasswordReply2\x91\x04\n" +
	"\vAuthService\x12b\n" +
	"\bRegister\x12\x1c.api.user.v1.RegisterRequest\x1a\x1a.api.user.v1.RegisterReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12V\n" +
	"\x05Login\x12\x19.api.user.v1.LoginRequest\x1a\x17.api.user.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12Z\n" +
	"\x06Logout\x12\x1a.api.user.v1.LogoutRequest\x1a\x18.api.user.v1.LogoutReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12m\n" +
	"\fRefreshToken\x12 .api.user.v1.RefreshTokenRequest\x1a\x1e.api.user.v1.RefreshTokenReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12{\n" +
	"\x0eChangePassword\x12\".api.user.v1.ChangePasswordRequest\x1a .api.user.v1.ChangePasswordReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/change-passwordB3\n" +
	"\vapi.user.v1P\x01Z\"kratos-micro-layout/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_auth_proto_rawDescOnce sync.Once
	file_user_v1_auth_proto_rawDescData []byte
)

func file_user_v1_auth_proto_rawDescGZIP() []byte {
	file_user_v1_auth_proto_rawDescOnce.Do(func() {
		file_user_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_auth_proto_rawDesc), len(file_user_v1_auth_proto_rawDesc)))
	})
	return file_user_v1_auth_proto_rawDescData
}

var file_user_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: api.user.v1.RegisterRequest
	(*RegisterReply)(nil),         // 1: api.user.v1.RegisterReply
	(*LoginRequest)(nil),          // 2: api.user.v1.LoginRequest
	(*TokenPair)(nil),             // 3: api.user.v1.TokenPair
	(*LoginReply)(nil),            // 4: api.user.v1.LoginReply
	(*LogoutRequest)(nil),         // 5: api.user.v1.LogoutRequest
	(*LogoutReply)(nil),           // 6: api.user.v1.LogoutReply
	(*RefreshTokenRequest)(nil),   // 7: api.user.v1.RefreshTokenRequest
	(*RefreshTokenReply)(nil),     // 8: api.user.v1.RefreshTokenReply
	(*ChangePasswordRequest)(nil), // 9: api.user.v1.ChangePasswordRequest
	(*ChangePasswordReply)(nil),   // 10: api.user.v1.ChangePasswordReply
}
var file_user_v1_auth_proto_depIdxs = []int32{
	3,  // 0: api.user.v1.LoginReply.tokens:type_name -> api.user.v1.TokenPair
	3,  // 1: api.user.v1.RefreshTokenReply.tokens:type_name -> api.user.v1.TokenPair
	0,  // 2: api.user.v1.AuthService.Register:input_type -> api.user.v1.RegisterRequest
	2,  // 3: api.user.v1.AuthService.Login:input_type -> api.user.v1.LoginRequest
	5,  // 4: api.user.v1.AuthService.Logout:input_type -> api.user.v1.LogoutRequest
	7,  // 5: api.user.v1.AuthService.RefreshToken:input_type -> api.user.v1.RefreshTokenRequest
	9,  // 6: api.user.v1.AuthService.ChangePassword:input_type -> api.user.v1.ChangePasswordRequest
	1,  // 7: api.user.v1.AuthService.Register:output_type -> api.user.v1.RegisterReply
	4,  // 8: api.user.v1.AuthService.Login:output_type -> api.user.v1.LoginReply
	6,  // 9: api.user.v1.AuthService.Logout:output_type -> api.user.v1.LogoutReply
	8,  // 10: api.user.v1.AuthService.RefreshToken:output_type -> api.user.v1.RefreshTokenReply
	10, // 11: api.user.v1.AuthService.ChangePassword:output_type -> api.user.v1.ChangePasswordReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_v1_auth_proto_init() }
func file_user_v1_auth_proto_init() {
	if File_user_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_auth_proto_rawDesc), len(file_user_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_auth_proto_goTypes,
		DependencyIndexes: file_user_v1_auth_proto_depIdxs,
		MessageInfos:      file_user_v1_auth_proto_msgTypes,
	}.Build()
	File_user_v1_auth_proto = out.File
	file_user_v1_auth_proto_goTypes = nil
	file_user_v1_auth_proto_depIdxs = nil
}
