// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason enumerates all user-domain error codes.
type ErrorReason int32

const (
	// Default unspecified error.
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// The requested user was not found.
	ErrorReason_USER_NOT_FOUND ErrorReason = 1
	// A user with the same username or email already exists.
	ErrorReason_USER_ALREADY_EXISTS ErrorReason = 2
	// The request contains invalid arguments.
	ErrorReason_USER_INVALID_ARGUMENT ErrorReason = 3
	// The supplied credentials are invalid.
	ErrorReason_AUTH_INVALID_CREDENTIALS ErrorReason = 4
	// The access or refresh token has expired.
	ErrorReason_AUTH_TOKEN_EXPIRED ErrorReason = 5
	// The token is malformed or tampered with.
	ErrorReason_AUTH_TOKEN_INVALID ErrorReason = 6
	// The request is not authenticated.
	ErrorReason_AUTH_UNAUTHORIZED ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "USER_NOT_FOUND",
		2: "USER_ALREADY_EXISTS",
		3: "USER_INVALID_ARGUMENT",
		4: "AUTH_INVALID_CREDENTIALS",
		5: "AUTH_TOKEN_EXPIRED",
		6: "AUTH_TOKEN_INVALID",
		7: "AUTH_UNAUTHORIZED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"USER_NOT_FOUND":           1,
		"USER_ALREADY_EXISTS":      2,
		"USER_INVALID_ARGUMENT":    3,
		"AUTH_INVALID_CREDENTIALS": 4,
		"AUTH_TOKEN_EXPIRED":       5,
		"AUTH_TOKEN_INVALID":       6,
		"AUTH_UNAUTHORIZED":        7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/error_reason.proto\x12\vapi.user.v1*\xd8\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x01\x12\x17\n" +
	"\x13USER_ALREADY_EXISTS\x10\x02\x12\x19\n" +
	"\x15USER_INVALID_ARGUMENT\x10\x03\x12\x1c\n" +
	"\x18AUTH_INVALID_CREDENTIALS\x10\x04\x12\x16\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\x05\x12\x16\n" +
	"\x12AUTH_TOKEN_INVALID\x10\x06\x12\x15\n" +
	"\x11AUTH_UNAUTHORIZED\x10\aB3\n" +
	"\vapi.user.v1P\x01Z\"kratos-micro-layout/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_user_v1_error_reason_proto_rawDescData []byte
)

func file_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)))
	})
	return file_user_v1_error_reason_proto_rawDescData
}

var file_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.user.v1.ErrorReason
}
var file_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_error_reason_proto_init() }
func file_user_v1_error_reason_proto_init() {
	if File_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_user_v1_error_reason_proto = out.File
	file_user_v1_error_reason_proto_goTypes = nil
	file_user_v1_error_reason_proto_depIdxs = nil
}
