version: v2
inputs:
  - directory: app/user_center/internal
plugins:
  - local: ["go", "run", "google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11"]
    out: app/user_center/internal
    opt: paths=source_relative
