// Package docs serves each service's generated OpenAPI document together with a
// Swagger UI for it, so a running service documents itself.
//
// `make api` runs protoc-gen-openapi once per api/<domain> (the openapi plugin
// in buf.gen.yaml, scoped per domain with --path) and writes
// pkg/docs/specs/<domain>/openapi.yaml. This
// package embeds that whole specs/ tree and serves the one document a service
// asks for, so each service's /swagger lists only the RPCs that service
// implements — not every domain's. The specs live in pkg/ (root module) rather
// than in api/ or app/<service> because go:embed cannot cross module boundaries.
//
// The UI is github.com/swaggo/http-swagger, the de-facto standard in Go: it
// renders the official swagger-ui-dist assets embedded in the binary (via
// github.com/swaggo/files/v2), so there is no CDN to reach and no HTML to
// maintain here. Mount everything from a service's HTTP server, naming the
// domain whose spec it should serve (the api/<domain> directory it implements):
//
//	docs.Register(srv, "user") // GET /swagger/ (UI) + GET /openapi.yaml (spec)
//
// The routes are raw handlers: they bypass the kratos middleware chain, so
// they are neither enveloped nor authenticated. This is a development aid —
// do not expose /swagger on a public production edge.
package docs

import (
	"bytes"
	"embed"
	"fmt"
	"net/http"
	"regexp"

	khttp "github.com/go-kratos/kratos/v3/transport/http"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// Route paths. Exported so a service can exempt them from a route-scoped
// middleware selector, or link to them from elsewhere.
const (
	// UIPath serves the Swagger UI. The UI itself lives under UIPath+"/" —
	// it is a bundle of assets, not a single page.
	UIPath = "/swagger"
	// SpecPath serves the OpenAPI 3 document.
	SpecPath = "/openapi.yaml"
)

// schemeName is the security scheme the UI's "Authorize" button fills in.
const schemeName = "bearerAuth"

// specs embeds every per-domain document as specs/<domain>/openapi.yaml. An
// embed.FS (rather than one //go:embed per file) means adding a domain needs no
// change here: `make api` drops the file in and Register(srv, domain) finds it.
//
//go:embed specs
var specs embed.FS

// specPath is where a domain's document lives inside the embedded FS.
func specPath(domain string) string { return "specs/" + domain + "/openapi.yaml" }

// Spec returns a domain's OpenAPI document exactly as served, security scheme
// included. It errors if that domain has no embedded spec (i.e. `make api` has
// not generated one, or the domain name does not match an api/<domain> dir).
func Spec(domain string) ([]byte, error) {
	raw, err := specs.ReadFile(specPath(domain))
	if err != nil {
		return nil, fmt.Errorf("docs: no embedded spec for domain %q (expected %s, generated by `make api`): %w", domain, specPath(domain), err)
	}
	return withSecurityScheme(raw), nil
}

// withSecurityScheme declares an HTTP bearer scheme and applies it to every
// operation, which is what makes Swagger UI show its native "Authorize" button
// (and what makes Postman/Apifox prompt for a token on import).
//
// protoc-gen-openapi only emits security schemes from gnostic's `openapi.v3`
// proto annotations, and adopting those would mean vendoring ~700 lines of
// openapiv3/*.proto into the repo plus a new buf module — a lot of ceremony
// for one scheme that every service in this template shares. Injecting it into
// the generated document keeps the API protos clean and the outcome identical.
//
// The scheme applies globally, so a domain's public RPCs (e.g. Register/Login/
// RefreshToken) are marked too. That is harmless in practice: a request with no
// token carries no Authorization header, and the auth selector ignores the
// header on routes it does not guard. Annotating per-operation instead would
// need the proto route described above.
func withSecurityScheme(doc []byte) []byte {
	out := componentsLine.ReplaceAllFunc(doc, func(m []byte) []byte {
		return append(append([]byte{}, m...), securitySchemesBlock...)
	})
	if bytes.Equal(out, doc) {
		// No components block to hang the scheme off (a domain without any
		// message would produce one); add it at the end.
		out = append(append([]byte{}, out...), []byte("components:\n"+securitySchemesBlock)...)
	}
	// Top-level `security` is what actually attaches the header; without it the
	// Authorize button shows but no request carries the token. Spliced in right
	// after the `openapi:` key so it lands at the top of the document.
	return openapiLine.ReplaceAllFunc(out, func(m []byte) []byte {
		return append(append([]byte{}, m...), securityBlock...)
	})
}

// securitySchemesBlock is indented to sit under `components:` (4 spaces), the
// style protoc-gen-openapi writes.
const securitySchemesBlock = `    securitySchemes:
        ` + schemeName + `:
            type: http
            scheme: bearer
            bearerFormat: JWT
`

// securityBlock is the document-level requirement, keyed by the scheme above.
const securityBlock = "security:\n    - " + schemeName + ": []\n"

var (
	// serversBlock matches the top-level "servers:" list protoc-gen-openapi
	// emits from each service's google.api.default_host. Those are
	// documentation placeholders (https://user.example.com), which would send
	// the UI's "try it out" calls to a host nobody runs; handleSpec rewrites
	// the list to the origin the request came in on.
	serversBlock = regexp.MustCompile(`(?m)^servers:\n(?:[ \t]+-[ \t]+url:[^\n]*\n)+`)
	// componentsLine matches the top-level `components:` key only — nested
	// occurrences are indented.
	componentsLine = regexp.MustCompile(`(?m)^components:\n`)
	// openapiLine matches the `openapi: <version>` key, always the first one
	// protoc-gen-openapi writes.
	openapiLine = regexp.MustCompile(`(?m)^openapi:[^\n]*\n`)
)

// Register mounts the docs routes for one domain on a kratos HTTP server. Call
// it after the generated service registrations in internal/server/http.go,
// passing the api/<domain> directory this service implements (e.g. "user").
// It panics if that domain has no embedded spec — a wiring mistake better
// surfaced loudly at startup than as a silently missing /swagger.
func Register(srv *khttp.Server, domain string) {
	doc, err := Spec(domain)
	if err != nil {
		panic(err)
	}
	ui := httpSwagger.Handler(
		httpSwagger.URL(SpecPath),
		// Keep the authorized token across a refresh or a browser restart.
		httpSwagger.PersistAuthorization(true),
	)
	// The UI resolves its assets relative to the page, so it must be served
	// under a trailing-slash prefix; /swagger alone redirects there.
	srv.HandlePrefix(UIPath+"/", ui)
	srv.HandleFunc(UIPath, func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, UIPath+"/", http.StatusMovedPermanently)
	})
	srv.HandleFunc(SpecPath, func(w http.ResponseWriter, r *http.Request) {
		handleSpec(w, r, doc)
	})
}

// handleSpec writes the document with its servers list pointed at the current
// origin, so "try it out" exercises the instance being browsed (including
// through the gateway or a TLS-terminating proxy).
func handleSpec(w http.ResponseWriter, r *http.Request, doc []byte) {
	body := serversBlock.ReplaceAllFunc(doc, func([]byte) []byte {
		// ReplaceAllFunc (not ReplaceAll) keeps "$" in the host literal.
		return []byte("servers:\n    - url: " + origin(r) + "\n")
	})
	w.Header().Set("Content-Type", "application/yaml; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	_, _ = w.Write(body)
}

// origin reconstructs the externally visible base URL of this request,
// trusting the forwarded headers a proxy sets.
func origin(r *http.Request) string {
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	if p := r.Header.Get("X-Forwarded-Proto"); p != "" {
		scheme = p
	}
	host := r.Host
	if h := r.Header.Get("X-Forwarded-Host"); h != "" {
		host = h
	}
	return scheme + "://" + host
}
