package middleware

import (
	"context"
	"strings"

	validateext "kratos-micro-layout/pkg/validate/v1"

	"buf.build/go/protovalidate"

	"github.com/go-kratos/kratos/v3/errors"
	"github.com/go-kratos/kratos/v3/middleware"
	"google.golang.org/protobuf/proto"
)

// ValidationFailedReason is the kratos error reason carried by requests the
// ProtoValidator rejects. It is transport-generic on purpose: pkg/middleware
// cannot know a domain's api error enum, so services that validate deeper in
// the stack keep using their own reason (e.g. ERROR_REASON_USER_INVALID_ARGUMENT).
const ValidationFailedReason = "VALIDATION_FAILED"

// ProtoValidator validates a request message against the buf.validate rules
// declared in the proto. It adds format rules (email, length, range) on top of
// presence, and runs identically on HTTP and gRPC so the two transports cannot
// drift. protovalidate caches the compiled rules per message type, so the cost
// after the first request is small.
//
// A failed validation becomes a kratos BadRequest whose message lists every
// violated field as "<field path>: <description>", joined with "; " so a client
// can split on it and highlight all offending inputs at once. The description
// is the (validate.v1.error_message) option declared beside the field's rules
// when present — the standard rules carry no message hook of their own — and
// protovalidate's own text otherwise (CEL rules keep their `message`).
// A compilation or other internal protovalidate failure is a server-side bug
// and is passed through unchanged so it surfaces as a 500.
//
// It has the shape kratos' own validate.Validator documents for a protovalidate
// integration; mount it through Validator below rather than through
// validate.Validator, which would rewrap the kratos error this returns.
func ProtoValidator(v any) error {
	msg, ok := v.(proto.Message)
	if !ok {
		return nil
	}
	err := protovalidate.Validate(msg)
	if err == nil {
		return nil
	}
	verr, ok := err.(*protovalidate.ValidationError)
	if !ok {
		return err
	}
	parts := make([]string, 0, len(verr.Violations))
	for _, violation := range verr.Violations {
		parts = append(parts, violationText(violation))
	}
	// The structured *ValidationError stays reachable through Unwrap, the way
	// kratos' own validate.Validator keeps the validator's error as the cause:
	// logs and the gRPC status can still get at the per-violation detail, while
	// the envelope shows only the joined message.
	return errors.BadRequest(ValidationFailedReason, strings.Join(parts, "; ")).WithCause(verr)
}

// selfValidator mirrors the interface kratos' validate.Validator looks for: a
// request type may carry its own Validate method (hand-written, or generated by
// a tool such as protoc-gen-validate) on top of the proto rules.
type selfValidator interface {
	Validate() error
}

// Validator returns the transport middleware that validates every request. It is
// a superset of kratos' validate.Validator, differing in two deliberate ways:
//
//   - It keeps an error that is already a kratos error untouched. kratos'
//     version rewraps with errors.BadRequest("VALIDATOR", err.Error()), and a
//     kratos error's Error() is the full "error: code = … reason = … message =
//     … metadata = …" rendering — the descriptions worded in the proto would
//     reach the client buried inside that string.
//   - The reason is ValidationFailedReason, not the hardcoded "VALIDATOR".
//
// Everything else matches: a request implementing Validate() error runs that
// first, the proto rules run second, and the original error is preserved as the
// cause.
func Validator() middleware.Middleware {
	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req any) (any, error) {
			if v, ok := req.(selfValidator); ok {
				if err := v.Validate(); err != nil {
					return nil, toBadRequest(err)
				}
			}
			if err := ProtoValidator(req); err != nil {
				return nil, toBadRequest(err)
			}
			return handler(ctx, req)
		}
	}
}

// toBadRequest passes a kratos error through as-is — its code, reason and
// message are already the ones the client should see — and wraps anything else
// into a 400 carrying ValidationFailedReason.
func toBadRequest(err error) error {
	if se, ok := err.(*errors.Error); ok {
		return se
	}
	return errors.BadRequest(ValidationFailedReason, err.Error()).WithCause(err)
}

// violationText renders one violation as "<field path>: <description>". The
// description prefers the field's (validate.v1.error_message) option, read back
// through the descriptor protovalidate attaches to the violation; fields without
// the option fall back to the rule's own text.
func violationText(violation *protovalidate.Violation) string {
	field := protovalidate.FieldPathString(violation.Proto.GetField())
	message := customMessage(violation)
	if message == "" {
		message = violation.Proto.GetMessage()
	}
	if field == "" {
		// A message-level rule: no field path to prefix.
		return message
	}
	return field + ": " + message
}

// customMessage returns the (validate.v1.error_message) option of the violated
// field, or "" when the field declares none.
//
// GetExtension hands back the plain Go value — a string here, not a *string —
// so the assertion must match; asserting a pointer silently yields "" and
// every failure text would fall back to protovalidate's stock wording.
func customMessage(violation *protovalidate.Violation) string {
	fd := violation.FieldDescriptor
	if fd == nil {
		return ""
	}
	opts := fd.Options()
	if opts == nil || !proto.HasExtension(opts, validateext.E_ErrorMessage) {
		return ""
	}
	message, _ := proto.GetExtension(opts, validateext.E_ErrorMessage).(string)
	return message
}
