// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: validate/v1/validate.proto

// The package mirrors this file's directory relative to the buf module root
// (the monorepo's pkg/ dir) and satisfies buf lint PACKAGE_DIRECTORY_MATCH /
// PACKAGE_VERSION_SUFFIX.

package validateext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_validate_v1_validate_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1100,
		Name:          "validate.v1.error_message",
		Tag:           "bytes,1100,opt,name=error_message",
		Filename:      "validate/v1/validate.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string error_message = 1100;
	E_ErrorMessage = &file_validate_v1_validate_proto_extTypes[0]
)

var File_validate_v1_validate_proto protoreflect.FileDescriptor

const file_validate_v1_validate_proto_rawDesc = "" +
	"\n" +
	"\x1avalidate/v1/validate.proto\x12\vvalidate.v1\x1a google/protobuf/descriptor.proto:F\n" +
	"\rerror_message\x12\x1d.google.protobuf.FieldOptions\x18\xcc\b \x01(\tR\ferrorMessage\x88\x01\x01B1Z/kratos-micro-layout/pkg/validate/v1;validateextb\x06proto3"

var file_validate_v1_validate_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_validate_v1_validate_proto_depIdxs = []int32{
	0, // 0: validate.v1.error_message:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_v1_validate_proto_init() }
func file_validate_v1_validate_proto_init() {
	if File_validate_v1_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_v1_validate_proto_rawDesc), len(file_validate_v1_validate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_validate_v1_validate_proto_goTypes,
		DependencyIndexes: file_validate_v1_validate_proto_depIdxs,
		ExtensionInfos:    file_validate_v1_validate_proto_extTypes,
	}.Build()
	File_validate_v1_validate_proto = out.File
	file_validate_v1_validate_proto_goTypes = nil
	file_validate_v1_validate_proto_depIdxs = nil
}
